version: '3'

services:
  whattowatch:
    image: whattowatch:0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: whattowatch
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - 5000:5000
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
        #    networks:
        #- app-network
    command: /home/node/app/node_modules/.bin/pm2-runtime start ecosystem.config.js
    
networks:
  default:
    external: true
    name: app-network

volumes:
  node_modules:
