scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: [
        'nodejs:3000',
      ]
        labels:
          service: 'movie-app'
          group: 'movie-app'
          name: 'movie-app'
  
  - job_name: 'flask_api'
    scrape_interval: 5s

    static_configs:
      - targets: [
        'flask_backend:5000',
      ]
        labels:
          service: 'flask-api'
          group: 'flask-api'
          name: 'flask-api'