version: '3'

services:
  nodejs:
    image: whattowatch:0.0.1
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "3000:3000"
    volumes:
      - ..:/home/node/app
      - /home/node/app/node_modules
    networks:
      - app-network
    command: ../scripts/wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/pm2-runtime start ecosystem.config.js
  

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: