FROM python:3.7 AS builder

RUN apt-get update && \ 
    apt-get upgrade -y && \
    apt-get install -y git gcc

WORKDIR /usr/src/app
COPY . .

RUN pip install --target=/usr/src/app/dependencies -r requirements.txt


FROM python:3.7
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app .
ENV PYTHONPATH "${PYTHONPATH}:/usr/src/app/dependencies"
EXPOSE 5000
#CMD ["python", "-u", "flask_app.py"]
